title: Krinal Joshi
description: Machine learning and Data enthusiasm
#show_downloads: true
theme: jekyll-theme-dinky
github:
  is_project_page: false

# author
author:
email: krinaljoshi@outlook.com

copyright:
year: 2024
name: krinal joshi
